In [17]:
import pandas as pd
import numpy as np
fandango=pd.read_csv('fandango_score_comparison.csv')
print(fandango.head(2))
print(fandango.index)

                             FILM  RottenTomatoes  RottenTomatoes_User  \
0  Avengers: Age of Ultron (2015)              74                   86
1               Cinderella (2015)              85                   80

   Metacritic  Metacritic_User  IMDB  Fandango_Stars  Fandango_Ratingvalue  \
0          66              7.1   7.8             5.0                   4.5
1          67              7.5   7.1             5.0                   4.5

   RT_norm  RT_user_norm         ...           IMDB_norm  RT_norm_round  \
0     3.70           4.3         ...                3.90            3.5
1     4.25           4.0         ...                3.55            4.5

   RT_user_norm_round  Metacritic_norm_round  Metacritic_user_norm_round  \
0                 4.5                    3.5                         3.5
1                 4.0                    3.5                         4.0

   IMDB_norm_round  Metacritic_user_vote_count  IMDB_user_vote_count  \
0              4.0                        1330                271107
1              3.5                         249                 65709

   Fandango_votes  Fandango_Difference
0           14846                  0.5
1           12640                  0.5

[2 rows x 22 columns]
RangeIndex(start=0, stop=146, step=1)

In [18]:
fandango.iloc[:5]
first_last=fandango.iloc[[0,fandango.shape[0]-1]]

The dataframe object has a `set_index()` method that allows us to pass in the name of the _column_ we want pandas to use as the Dataframe index. By default, pandas will create a new dataframe, index it by the values in the column we specify, then drop that column. The `set_index()` method has a few parameters that allow us to tweak this behavior:

*   `inplace`: If set to `True`, this parameter will set the index for the current, "live" dataframe, instead of returning a new dataframe.
*   `drop`: If set to `False`, this parameter will keep the column we specified as the index, instead of dropping it.

### Do
*   Use the pandas dataframe method [`set_index`](http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.set_index.html) to assign the `FILM` column as the custom index for the dataframe. Also, specify that we don't want to drop the `FILM` column from the dataframe. We want to keep the original dataframe, so assign the new one to `fandango_films`.

*   Display the index for `fandango_films` using the `index` attribute and the `print` function.

In [19]:
fandango_films=fandango.set_index(fandango['FILM'],inplace=False,drop=False)
print(fandango_films.index)

Index(['Avengers: Age of Ultron (2015)', 'Cinderella (2015)', 'Ant-Man (2015)',
       'Do You Believe? (2015)', 'Hot Tub Time Machine 2 (2015)',
       'The Water Diviner (2015)', 'Irrational Man (2015)', 'Top Five (2014)',
       'Shaun the Sheep Movie (2015)', 'Love & Mercy (2015)',
       ...
       'The Woman In Black 2 Angel of Death (2015)', 'Danny Collins (2015)',
       'Spare Parts (2015)', 'Serena (2015)', 'Inside Out (2015)',
       'Mr. Holmes (2015)', ''71 (2015)', 'Two Days, One Night (2014)',
       'Gett: The Trial of Viviane Amsalem (2015)',
       'Kumiko, The Treasure Hunter (2015)'],
      dtype='object', name='FILM', length=146)

<div id="body" class="MissionLearn__section___3Mtj9 MissionMarkup__root___3FAB8"><div><p>Now that we have a custom index, we can select a row by film name instead of row number (which is the default integer index).  We can select rows using the custom index by either:</p>
<ol>
<li>Using the <code>loc[]</code> method (the same way we would the <code>iloc[]</code> method)</li>
<li>Creating a slice using bracket notation</li>
</ol>
</div><div class="MissionMarkup__code_block___2vANs DqEditor__root___2C-3R"><textarea autocomplete="off" style="display: none;"># Slice using either bracket notation or loc[]
fandango_films["Avengers: Age of Ultron (2015)":"Hot Tub Time Machine 2 (2015)"]
fandango_films.loc["Avengers: Age of Ultron (2015)":"Hot Tub Time Machine 2 (2015)"]

# Specific movie
fandango_films.loc['Kumiko, The Treasure Hunter (2015)']

# Selecting list of movies
movies = ['Kumiko, The Treasure Hunter (2015)', 'Do You Believe? (2015)', 'Ant-Man (2015)']
fandango_films.loc[movies]</textarea><div class="CodeMirror cm-s-dq-light CodeMirror-wrap"><div style="overflow: hidden; position: relative; width: 3px; height: 0px; top: 7.5px; left: 3.63636px;"><textarea autocorrect="off" autocapitalize="off" spellcheck="false" style="position: absolute; bottom: -1em; padding: 0px; width: 1000px; height: 1em; outline: none;" tabindex="0"></textarea></div><div class="CodeMirror-vscrollbar" cm-not-content="true"><div style="min-width: 1px; height: 0px;"></div></div><div class="CodeMirror-hscrollbar" cm-not-content="true"><div style="height: 100%; min-height: 1px; width: 0px;"></div></div><div class="CodeMirror-scrollbar-filler" cm-not-content="true"></div><div class="CodeMirror-gutter-filler" cm-not-content="true"></div><div class="CodeMirror-scroll" tabindex="-1"><div class="CodeMirror-sizer" style="margin-left: 0px; margin-bottom: -15px; border-right-width: 15px; min-height: 244px; padding-right: 0px; padding-bottom: 0px;"><div style="position: relative; top: 0px;"><div class="CodeMirror-lines" role="presentation"><div role="presentation" style="position: relative; outline: none;"><div class="CodeMirror-measure"><pre><span>xxxxxxxxxx</span></pre></div><div class="CodeMirror-measure"></div><div style="position: relative; z-index: 1;"></div><div class="CodeMirror-cursors"><div class="CodeMirror-cursor" style="left: 3.63636px; top: 0px; height: 17.2727px;">&nbsp;</div></div><div class="CodeMirror-code" role="presentation" style=""><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span class="cm-comment"># Slice using either bracket notation or loc[]</span></span></pre><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span class="cm-variable">fandango_films</span>[<span class="cm-string">"Avengers: Age of Ultron (2015)"</span>:<span class="cm-string">"Hot Tub Time Machine 2 (2015)"</span>]</span></pre><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span class="cm-variable">fandango_films</span>.<span class="cm-property">loc</span>[<span class="cm-string">"Avengers: Age of Ultron (2015)"</span>:<span class="cm-string">"Hot Tub Time Machine 2 (2015)"</span>]</span></pre><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span cm-text="">&#8203;</span></span></pre><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span class="cm-comment"># Specific movie</span></span></pre><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span class="cm-variable">fandango_films</span>.<span class="cm-property">loc</span>[<span class="cm-string">'Kumiko, The Treasure Hunter (2015)'</span>]</span></pre><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span cm-text="">&#8203;</span></span></pre><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span class="cm-comment"># Selecting list of movies</span></span></pre><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span class="cm-variable">movies</span> <span class="cm-operator">=</span> [<span class="cm-string">'Kumiko, The Treasure Hunter (2015)'</span>, <span class="cm-string">'Do You Believe? (2015)'</span>, <span class="cm-string">'Ant-Man (2015)'</span>]</span></pre><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span class="cm-variable">fandango_films</span>.<span class="cm-property">loc</span>[<span class="cm-variable">movies</span>]</span></pre></div></div></div></div></div><div style="position: absolute; height: 15px; width: 1px; border-bottom: 0px solid transparent; top: 244px;"></div><div class="CodeMirror-gutters" style="display: none; height: 259px;"></div></div></div></div><div>
<p>When we select multiple rows, pandas returns a dataframe. When we select an individual row, however, it returns a Series object instead.  Either way, pandas will maintain the original integer index, even if we specify a custom index. That means we can still select by row number.</p></div></div>

### DO
<ul>
<li>Select the following movies from <code>fandango_films</code> (in the order in which they appear), and assign them to <code>best_movies_ever</code>:<ul>
<li>"The Lazarus Effect (2015)"</li>
<li>"Gett: The Trial of Viviane Amsalem (2015)"</li>
<li>"Mr. Holmes (2015)"</li>
</ul>
</li>
</ul>

In [20]:
list_of_best_movies=['The Lazarus Effect (2015)','Gett: The Trial of Viviane Amsalem (2015)','Mr. Holmes (2015)']
best_movies_ever=fandango_films.loc[list_of_best_movies]
best_movies_ever

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
The Lazarus Effect (2015),The Lazarus Effect (2015),14,23,31,4.9,5.2,3.0,3.0,0.70,1.15,...,2.6,0.5,1.0,1.5,2.5,2.5,62,17691,1651,0.0
Gett: The Trial of Viviane Amsalem (2015),Gett: The Trial of Viviane Amsalem (2015),100,81,90,7.3,7.8,3.5,3.5,5.00,4.05,...,3.9,5.0,4.0,4.5,3.5,4.0,19,1955,59,0.0
Mr. Holmes (2015),Mr. Holmes (2015),87,78,67,7.9,7.4,4.0,4.0,4.35,3.90,...,3.7,4.5,4.0,3.5,4.0,3.5,33,7367,1348,0.0

<div><p>Recall that a dataframe object represents both rows and columns as Series objects. The <code>apply()</code> method in pandas allows us to specify Python logic that we want to evaluate over the Series objects in a dataframe.  Here are some examples of what we can accomplish using the <code>apply()</code> method:</p>
<ul>
<li>Calculate the standard deviations for each numeric column</li>
<li>Lowercase all film names in the <code>FILM</code> column</li>
</ul>
<p>The <code>apply()</code> method requires us to pass in the vectorized operation we want to apply over each Series object.  The method runs over the dataframe's columns by default, but we can use the <code>axis</code> parameter to change this (which we'll do later).  If the vectorized operation usually returns a single value (such as the NumPy <code>std()</code> function), it will return a Series object containing the computed value for each column.  If it usually returns a value for each element (such as multiplying or dividing by 2), it will transform all of the values and return them as a dataframe.</p>
<p>In the following code cell, we select only the <em>float</em> columns, and assign the dataframe containing them to <code>float_df</code>.  Then, we pass in the NumPy function <code>std()</code> as a lambda function to the dataframe method <code>apply()</code> in order to calculate the standard deviation of each column.  Under the hood, pandas uses vectorized operations to apply the NumPy function for each iteration of the <code>apply()</code> method. It then returns a final Series object containing the standard deviations for each column (i.e., the film ratings).</p></div>

In [24]:
# returns the data types as a Series
types = fandango_films.dtypes
# filter data types to just floats, index attributes returns just column names
float_columns = types[types.values == 'float64'].index
# use bracket notation to filter columns to just float columns
float_df = fandango_films[float_columns]
# print(float_df)
# `x` is a Series object representing a column
deviations = float_df.apply(lambda x: np.std(x))

print(deviations)

Metacritic_User               1.505529
IMDB                          0.955447
Fandango_Stars                0.538532
Fandango_Ratingvalue          0.501106
RT_norm                       1.503265
RT_user_norm                  0.997787
Metacritic_norm               0.972522
Metacritic_user_nom           0.752765
IMDB_norm                     0.477723
RT_norm_round                 1.509404
RT_user_norm_round            1.003559
Metacritic_norm_round         0.987561
Metacritic_user_norm_round    0.785412
IMDB_norm_round               0.501043
Fandango_Difference           0.152141
dtype: float64

<div id="body" class="MissionLearn__section___3Mtj9 MissionMarkup__root___3FAB8"><div><p>Recall that the NumPy <code>std()</code> method returns a single computed value when we apply it over a Series.  In the previous code cell, the <code>apply()</code> method returned a single value for each column for this reason.  </p>
<p>If we use a NumPy function that returns a value for each element in a Series, we can transform all of the values in each column and return a dataframe with those new values instead.  Here's an example:</p>
</div><div class="MissionMarkup__code_block___2vANs DqEditor__root___2C-3R"><textarea autocomplete="off" style="display: none;">float_df.apply(lambda x: x*2)</textarea><div class="CodeMirror cm-s-dq-light CodeMirror-wrap"><div style="overflow: hidden; position: relative; width: 3px; height: 0px; top: 7.5px; left: 3.63636px;"><textarea autocorrect="off" autocapitalize="off" spellcheck="false" style="position: absolute; bottom: -1em; padding: 0px; width: 1000px; height: 1em; outline: none;" tabindex="0"></textarea></div><div class="CodeMirror-vscrollbar" cm-not-content="true"><div style="min-width: 1px; height: 0px;"></div></div><div class="CodeMirror-hscrollbar" cm-not-content="true"><div style="height: 100%; min-height: 1px; width: 0px;"></div></div><div class="CodeMirror-scrollbar-filler" cm-not-content="true"></div><div class="CodeMirror-gutter-filler" cm-not-content="true"></div><div class="CodeMirror-scroll" tabindex="-1"><div class="CodeMirror-sizer" style="margin-left: 0px; margin-bottom: -15px; border-right-width: 15px; min-height: 36px; padding-right: 0px; padding-bottom: 0px;"><div style="position: relative; top: 0px;"><div class="CodeMirror-lines" role="presentation"><div role="presentation" style="position: relative; outline: none;"><div class="CodeMirror-measure"><pre><span>xxxxxxxxxx</span></pre></div><div class="CodeMirror-measure"></div><div style="position: relative; z-index: 1;"></div><div class="CodeMirror-cursors"><div class="CodeMirror-cursor" style="left: 3.63636px; top: 0px; height: 17.2727px;">&nbsp;</div></div><div class="CodeMirror-code" role="presentation"><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span class="cm-variable">float_df</span>.<span class="cm-property">apply</span>(<span class="cm-keyword">lambda</span> <span class="cm-variable">x</span>: <span class="cm-variable">x</span><span class="cm-operator">*</span><span class="cm-number">2</span>)</span></pre></div></div></div></div></div><div style="position: absolute; height: 15px; width: 1px; border-bottom: 0px solid transparent; top: 36px;"></div><div class="CodeMirror-gutters" style="display: none; height: 51px;"></div></div></div></div><div>
<p>This will double each of the ratings in the float columns and return a new dataframe, instead of modifying the object in place.</p></div></div>

<ul>
<li>Use the <code>apply()</code> method on <code>float_df</code> to halve each value, and assign the result to <code>halved_df</code>.  Then, print the first row.</li>
</ul>

In [27]:
halved_df=float_df.apply(lambda x: x/2)
print(halved_df.iloc[0])

Metacritic_User               3.550
IMDB                          3.900
Fandango_Stars                2.500
Fandango_Ratingvalue          2.250
RT_norm                       1.850
RT_user_norm                  2.150
Metacritic_norm               1.650
Metacritic_user_nom           1.775
IMDB_norm                     1.950
RT_norm_round                 1.750
RT_user_norm_round            2.250
Metacritic_norm_round         1.750
Metacritic_user_norm_round    1.750
IMDB_norm_round               2.000
Fandango_Difference           0.250
Name: Avengers: Age of Ultron (2015), dtype: float64

<div id="body" class="MissionLearn__section___3Mtj9 MissionMarkup__root___3FAB8"><div><p>So far we've used the default behavior of the <code>apply()</code> method, which operates over the columns in a Dataframe.  To apply a function over the rows in a dataframe (which pandas treats as Series objects), we need to set the <code>axis</code> parameter to <code>1</code>.  Applying over the rows allows us to do things like calculate the standard deviation of multiple column values for each movie:</p>
</div><div class="MissionMarkup__code_block___2vANs DqEditor__root___2C-3R"><textarea autocomplete="off" style="display: none;">rt_mt_user = float_df[['RT_user_norm', 'Metacritic_user_nom']]
rt_mt_user.apply(lambda x: np.std(x), axis=1)</textarea><div class="CodeMirror cm-s-dq-light CodeMirror-wrap"><div style="overflow: hidden; position: relative; width: 3px; height: 0px; top: 7.5px; left: 3.63636px;"><textarea autocorrect="off" autocapitalize="off" spellcheck="false" style="position: absolute; bottom: -1em; padding: 0px; width: 1000px; height: 1em; outline: none;" tabindex="0"></textarea></div><div class="CodeMirror-vscrollbar" cm-not-content="true"><div style="min-width: 1px; height: 0px;"></div></div><div class="CodeMirror-hscrollbar" cm-not-content="true"><div style="height: 100%; min-height: 1px; width: 0px;"></div></div><div class="CodeMirror-scrollbar-filler" cm-not-content="true"></div><div class="CodeMirror-gutter-filler" cm-not-content="true"></div><div class="CodeMirror-scroll" tabindex="-1"><div class="CodeMirror-sizer" style="margin-left: 0px; margin-bottom: -15px; border-right-width: 15px; min-height: 71px; padding-right: 0px; padding-bottom: 0px;"><div style="position: relative; top: 0px;"><div class="CodeMirror-lines" role="presentation"><div role="presentation" style="position: relative; outline: none;"><div class="CodeMirror-measure"><pre><span>xxxxxxxxxx</span></pre></div><div class="CodeMirror-measure"></div><div style="position: relative; z-index: 1;"></div><div class="CodeMirror-cursors"><div class="CodeMirror-cursor" style="left: 3.63636px; top: 0px; height: 17.2727px;">&nbsp;</div></div><div class="CodeMirror-code" role="presentation"><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span class="cm-variable">rt_mt_user</span> <span class="cm-operator">=</span> <span class="cm-variable">float_df</span>[[<span class="cm-string">'RT_user_norm'</span>, <span class="cm-string">'Metacritic_user_nom'</span>]]</span></pre><pre class=" CodeMirror-line " role="presentation"><span role="presentation" style="padding-right: 0.1px;"><span class="cm-variable">rt_mt_user</span>.<span class="cm-property">apply</span>(<span class="cm-keyword">lambda</span> <span class="cm-variable">x</span>: <span class="cm-variable">np</span>.<span class="cm-property">std</span>(<span class="cm-variable">x</span>), <span class="cm-variable">axis</span><span class="cm-operator">=</span><span class="cm-number">1</span>)</span></pre></div></div></div></div></div><div style="position: absolute; height: 15px; width: 1px; border-bottom: 0px solid transparent; top: 71px;"></div><div class="CodeMirror-gutters" style="display: none; height: 86px;"></div></div></div></div><div>
<p>The code above filters the dataframe down to the two columns we want. Because <code>std()</code> returns a value for each iteration, it then returns a Series object containing the standard deviation of each movie's ratings from <code>RT_user_norm</code> and <code>Metacritic_user_nom</code>.</p></div></div>

### DO
<ul>
<li>Use the <code>apply()</code> method to calculate the average of each movie's values for <code>RT_user_norm</code> and <code>Metacritic_user_nom</code>, and assign the result to the variable <code>rt_mt_means</code>.  </li>
<li>Display the first five values in <code>rt_mt_means</code>.</li>
</ul>

In [34]:
rt_mt_user = float_df[['RT_user_norm', 'Metacritic_user_nom']]
print(rt_mt_user)
rt_mt_means=rt_mt_user.apply(lambda x: np.mean(x), axis=1)
rt_mt_means.head(1)

                                                RT_user_norm  \
FILM
Avengers: Age of Ultron (2015)                          4.30
Cinderella (2015)                                       4.00
Ant-Man (2015)                                          4.50
Do You Believe? (2015)                                  4.20
Hot Tub Time Machine 2 (2015)                           1.40
The Water Diviner (2015)                                3.10
Irrational Man (2015)                                   2.65
Top Five (2014)                                         3.20
Shaun the Sheep Movie (2015)                            4.10
Love & Mercy (2015)                                     4.35
Far From The Madding Crowd (2015)                       3.85
Black Sea (2015)                                        3.00
Leviathan (2014)                                        3.95
Unbroken (2014)                                         3.50
The Imitation Game (2014)                               4.60
Taken 3 (2015)                                          2.30
Ted 2 (2015)                                            2.90
Southpaw (2015)                                         4.00
Night at the Museum: Secret of the Tomb (2014)          2.90
Pixels (2015)                                           2.70
McFarland, USA (2015)                                   4.45
Insidious: Chapter 3 (2015)                             2.80
The Man From U.N.C.L.E. (2015)                          4.00
Run All Night (2015)                                    2.95
Trainwreck (2015)                                       3.70
Selma (2014)                                            4.30
Ex Machina (2015)                                       4.30
Still Alice (2015)                                      4.25
Wild Tales (2014)                                       4.60
The End of the Tour (2015)                              4.45
...                                                      ...
Clouds of Sils Maria (2015)                             3.35
Testament of Youth (2015)                               3.95
Infinitely Polar Bear (2015)                            3.80
Phoenix (2015)                                          4.05
The Wolfpack (2015)                                     3.65
The Stanford Prison Experiment (2015)                   4.35
Tangerine (2015)                                        4.30
Magic Mike XXL (2015)                                   3.20
Home (2015)                                             3.25
The Wedding Ringer (2015)                               3.30
Woman in Gold (2015)                                    4.05
The Last Five Years (2015)                              3.00
Mission: Impossible â€“ Rogue Nation (2015)             4.50
Amy (2015)                                              4.55
Jurassic World (2015)                                   4.05
Minions (2015)                                          2.60
Max (2015)                                              3.65
Paul Blart: Mall Cop 2 (2015)                           1.80
The Longest Ride (2015)                                 3.65
The Lazarus Effect (2015)                               1.15
The Woman In Black 2 Angel of Death (2015)              1.25
Danny Collins (2015)                                    3.75
Spare Parts (2015)                                      4.15
Serena (2015)                                           1.25
Inside Out (2015)                                       4.50
Mr. Holmes (2015)                                       3.90
'71 (2015)                                              4.10
Two Days, One Night (2014)                              3.90
Gett: The Trial of Viviane Amsalem (2015)               4.05
Kumiko, The Treasure Hunter (2015)                      3.15

                                                Metacritic_user_nom
FILM
Avengers: Age of Ultron (2015)                                 3.55
Cinderella (2015)                                              3.75
Ant-Man (2015)                                                 4.05
Do You Believe? (2015)                                         2.35
Hot Tub Time Machine 2 (2015)                                  1.70
The Water Diviner (2015)                                       3.40
Irrational Man (2015)                                          3.80
Top Five (2014)                                                3.40
Shaun the Sheep Movie (2015)                                   4.40
Love & Mercy (2015)                                            4.25
Far From The Madding Crowd (2015)                              3.75
Black Sea (2015)                                               3.30
Leviathan (2014)                                               3.60
Unbroken (2014)                                                3.25
The Imitation Game (2014)                                      4.10
Taken 3 (2015)                                                 2.30
Ted 2 (2015)                                                   3.25
Southpaw (2015)                                                4.10
Night at the Museum: Secret of the Tomb (2014)                 2.90
Pixels (2015)                                                  2.65
McFarland, USA (2015)                                          3.60
Insidious: Chapter 3 (2015)                                    3.45
The Man From U.N.C.L.E. (2015)                                 3.95
Run All Night (2015)                                           3.65
Trainwreck (2015)                                              3.00
Selma (2014)                                                   3.55
Ex Machina (2015)                                              3.95
Still Alice (2015)                                             3.90
Wild Tales (2014)                                              4.40
The End of the Tour (2015)                                     3.75
...                                                             ...
Clouds of Sils Maria (2015)                                    3.55
Testament of Youth (2015)                                      3.95
Infinitely Polar Bear (2015)                                   3.95
Phoenix (2015)                                                 4.00
The Wolfpack (2015)                                            3.50
The Stanford Prison Experiment (2015)                          4.25
Tangerine (2015)                                               3.65
Magic Mike XXL (2015)                                          2.70
Home (2015)                                                    3.65
The Wedding Ringer (2015)                                      1.65
Woman in Gold (2015)                                           3.60
The Last Five Years (2015)                                     3.45
Mission: Impossible â€“ Rogue Nation (2015)                    4.00
Amy (2015)                                                     4.40
Jurassic World (2015)                                          3.50
Minions (2015)                                                 2.85
Max (2015)                                                     2.95
Paul Blart: Mall Cop 2 (2015)                                  1.20
The Longest Ride (2015)                                        2.40
The Lazarus Effect (2015)                                      2.45
The Woman In Black 2 Angel of Death (2015)                     2.20
Danny Collins (2015)                                           3.55
Spare Parts (2015)                                             3.55
Serena (2015)                                                  2.65
Inside Out (2015)                                              4.45
Mr. Holmes (2015)                                              3.95
'71 (2015)                                                     3.75
Two Days, One Night (2014)                                     4.40
Gett: The Trial of Viviane Amsalem (2015)                      3.65
Kumiko, The Treasure Hunter (2015)                             3.20

[146 rows x 2 columns]

FILM
Avengers: Age of Ultron (2015)    3.925
dtype: float64